- name: Initial Config
  hosts: all
  become: true
  gather_facts: no
  roles:
    - role: init

- name: Setting Fact - MASTER_IPS
  hosts: masters
  gather_facts: no
  tasks:
    - name: Get master node ip
      set_fact:
        master_ips: "{{ master_ips | default([]) + [ansible_ssh_host] }}"
      # delegate_to: "{{ item }}"
      with_inventory_hostnames: masters

- name: Configure Principal Master Node
  hosts: "{{ hostvars['localhost']['primary_master'] }}"
  become: true
  roles:
    - role: principal


- name: Publish Node Token to Nodes
  hosts: all
  become: true
  tasks:
    - name: Read cluster node-token
      slurp:
        src: /var/lib/rancher/rke2/server/node-token
      register: node_token_b64
      when: inventory_hostname == primary_master

    - name: Set cluster facts on all nodes
      set_fact:
        master_url: "https://{{ ansible_host }}:9345"
        node_token: "{{ node_token_b64.content | b64decode }}"
      # delegate_to: "{{ primary_master }}"
      run_once: true

- name: Adding Master Nodes
  hosts: masters
  become: true
  roles:
    - role: server

- name: Adding Worker Nodes
  hosts: workers
  become: true
  roles:
    - role: agent