#inventory
---
all:
  vars:
  hosts:
    master1:
      ansible_host: "192.168.122.113"
      ansible_user: "snake"
      hostname: "rke2-master.local"
      user: 
    # master2:
    #   ansible_host:
    #   hostname:
    # master3:
    #   ansible_host:
    #   hostname:
    worker1:
      ansible_user: "snake"
      ansible_host: "192.168.122.192"
      hostname: "rke2-worker-1.local"
    worker2:
      ansible_user: "snake"
      ansible_host: "192.168.122.138"
      hostname: "rke2-worker-2.local"
    # worker3:
    #   ansible_host:
    #   hostname:
  children:
    masters:
      hosts:
        master1:
        # master2:
        # master3:
    workers:
      hosts:
        worker1:
        worker2:
        # worker3:
