#inventory
---
all:
  vars:
  hosts:
    master1:
      ansible_host:
      hostname:
    master2:
      ansible_host:
      hostname:
    master3:
      ansible_host:
      hostname:
    worker1:
      ansible_host:
      hostname:
    worker2:
      ansible_host:
      hostname:
    worker3:
      ansible_host:
      hostname:
  children:
    masters:
      hosts:
        master1:
        master2:
        master3:
    workers:
      hosts:
        worker1:
        worker2:
        worker3:
