---
primary_master: master1
cluster_cidr: 10.132.0.0/16
service_cidr: 172.30.0.0/16
cluster_dns: 172.30.0.10
rancher_hostname: rancher.local
kernel_modules:
- br_netfilter
- ip6_udp_tunnel
- ip_set
- ip_set_hash_ip
- ip_set_hash_net
- iptable_filter
- iptable_nat
- iptable_mangle
- iptable_raw
- nf_conntrack_netlink
- nf_conntrack
# - nf_conntrack_ipv4
- nf_defrag_ipv4
- nf_nat
# - nf_nat_ipv4
# - nf_nat_masquerade_ipv4
- nfnetlink
- udp_tunnel
- veth
- vxlan
- x_tables
- xt_addrtype
- xt_conntrack
- xt_comment
- xt_mark
- xt_multiport
- xt_nat
- xt_recent
- xt_set
- xt_statistic
- xt_tcpudp
tcp_ports:
- 22
- 80
- 443
- 2376
- 2379
- 2380
- 6443
- 9099
- 9796
- 10250
- 10254
- 30000-32767
udp_ports:
- 8472
- 30000-32767
