---
- name: Create cattle system namespace
  shell: "/usr/local/bin/kubectl create namespace cattle-system"
  ignore_errors: yes
  environment:
    KUBECONFIG: /etc/rancher/rke2/rke2.yaml

- name: Apply Cert Manager CRDS
  shell: "/usr/local/bin/kubectl apply --validate=false -f https://github.com/cert-manager/cert-manager/releases/download/v1.13.1/cert-manager.crds.yaml"
  environment:
    KUBECONFIG: /etc/rancher/rke2/rke2.yaml

- name: Create Cert Manager Namespace
  shell: "/usr/local/bin/kubectl create namespace cert-manager"
  ignore_errors: yes
  environment:
    KUBECONFIG: /etc/rancher/rke2/rke2.yaml

- name: Copy ADDITIONAL CA's pem file
  ansible.builtin.copy:
    src: ./certs/tls-rancher/ca-additional.pem
    dest: /root/ca-additional.pem
  environment:
    KUBECONFIG: /etc/rancher/rke2/rke2.yaml

- name: Create Additional CAs Secret
  shell: "/usr/local/bin/kubectl -n cattle-system create secret generic tls-ca-additional --from-file=ca-additional.pem=/root/ca-additional.pem"
  ignore_errors: yes
  environment:
    KUBECONFIG: /etc/rancher/rke2/rke2.yaml

- name: Copy AC-INTERNA PEM
  ansible.builtin.copy:
    src: ./certs/tls-rancher/internal-ca.pem
    dest: /root/internal-ca.pem
  environment:
    KUBECONFIG: /etc/rancher/rke2/rke2.yaml

- name: Create TLS-CA secret
  shell: "/usr/local/bin/kubectl -n cattle-system create secret generic tls-ca --from-file=cacerts.pem=/root/internal-ca.pem"
  ignore_errors: yes
  environment:
    KUBECONFIG: /etc/rancher/rke2/rke2.yaml

- name: Copy TLS key file
  ansible.builtin.copy:
    src: ./certs/tls-rancher/rancher.local.key
    dest: /root/tls.key
  environment:
    KUBECONFIG: /etc/rancher/rke2/rke2.yaml

- name: Copy TLS cert file
  ansible.builtin.copy:
    src: ./certs/tls-rancher/rancher.local.crt
    dest: /root/tls.crt
  environment:
    KUBECONFIG: /etc/rancher/rke2/rke2.yaml

- name: Create TLS key and cert secret
  shell: "/usr/local/bin/kubectl -n cattle-system create secret tls tls-rancher-ingress --cert=/root/tls.crt --key=/root/tls.key"
  ignore_errors: yes
  environment:
    KUBECONFIG: /etc/rancher/rke2/rke2.yaml

- name: Install Rancher
  shell: "/usr/local/bin/helm install rancher rancher-stable/rancher --namespace cattle-system --set hostname={{ rancher_hostname }} --set additionalTrustedCAs=true --set privateCA=true --set ingress.tls.source=secret"
  environment:
    KUBECONFIG: /etc/rancher/rke2/rke2.yaml
