---
apiVersion: management.cattle.io/v3
kind: ClusterRegistrationToken
metadata:
  name: default-token
  namespace: downstream-custom-dev-cilium
  labels:
    app.kubernetes.io/managed-by: gitops
    rancher.cattle.io/cni: cilium
spec:
  clusterName: downstream-custom-dev-cilium
